require: rubocop-rspec
inherit_from: .rubocop_todo.yml

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLineAfterGuardClause:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 12

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Exclude:
    - 'bin/rails'
    - 'bin/rake'

Style/FormatString:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# Offense count: 2
Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/LineLength:
  Max: 120
  AllowHeredoc: true
  AllowURI: true
  Exclude:
  - 'config/initializers/**'
  - 'db/schema.rb'

Metrics/BlockLength:
  Exclude:
  - 'db/schema.rb'